<?php
declare(strict_types=1);
session_start();
require_once dirname(__DIR__) . '/api/config.php';
if (empty($_SESSION['admin_id'])) { header('Location: login.php'); exit; }
$db = db();
$revenue = (float) $db->query("SELECT COALESCE(SUM(total),0) FROM orders WHERE payment_status = 'payment_approved'")->fetchColumn();
$orderCount = (int) $db->query('SELECT COUNT(*) FROM orders')->fetchColumn();
$customerCount = (int) $db->query('SELECT COUNT(DISTINCT customer_email) FROM orders')->fetchColumn();
$pending = (int) $db->query("SELECT COUNT(*) FROM orders WHERE payment_status IN ('awaiting_payment','payment_pending_confirmation')")->fetchColumn();
$chartStart = new DateTimeImmutable('first day of this month -5 months');
$chartEnd = new DateTimeImmutable('first day of this month');
$sales = $db->prepare("SELECT DATE_FORMAT(created_at,'%Y-%m') month_key, SUM(total) total FROM orders WHERE payment_status = 'payment_approved' AND created_at >= ? GROUP BY month_key ORDER BY month_key");
$sales->execute([$chartStart->format('Y-m-d')]);
$salesByMonth = array_column($sales->fetchAll(), 'total', 'month_key');
$months = [];
for ($month = $chartStart; $month <= $chartEnd; $month = $month->modify('+1 month')) $months[] = ['label' => $month->format('M'), 'total' => (float) ($salesByMonth[$month->format('Y-m')] ?? 0)];
$maxSales = max(1, ...array_column($months, 'total'));
function overviewEscape(string $value): string { return htmlspecialchars($value, ENT_QUOTES, 'UTF-8'); }
?><!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Overview - Electra admin</title><link rel="stylesheet" href="admin.css"><style>.overview-grid{display:grid;grid-template-columns:1.45fr 1fr;gap:22px}.chart-card{min-width:0}.chart{display:grid;grid-template-columns:repeat(6,1fr);align-items:end;gap:12px;height:250px;padding:20px 8px 28px;border-bottom:1px solid var(--line);background:repeating-linear-gradient(to bottom,transparent 0,transparent 24%,#eee9df 25%)}.bar-wrap{display:grid;grid-template-rows:1fr auto;height:100%;gap:9px;min-width:0}.bar-area{height:100%;display:flex;align-items:flex-end;justify-content:center}.bar{width:min(44px,70%);min-height:3px;border-radius:6px 6px 2px 2px;background:linear-gradient(180deg,var(--gold-light),var(--gold));}.bar-wrap small{text-align:center;color:var(--muted);font-size:11px}.chart-value{display:block;margin-bottom:5px;color:#8a672d;font-size:10px;font-weight:700;text-align:center;white-space:nowrap}.overview-links{display:flex;flex-wrap:wrap;gap:10px;margin-top:20px}.overview-links a{padding:11px 14px;border-radius:6px;background:var(--black);color:var(--gold-light);font-size:12px;font-weight:700;text-decoration:none}.stat-grid{display:grid;grid-template-columns:repeat(4,1fr);gap:16px;margin-bottom:22px}.stat-card{padding:20px;border:1px solid var(--line);border-radius:8px;background:#fff}.stat-card span,.stat-card small{display:block;color:var(--muted);font-size:13px}.stat-card strong{display:block;margin:12px 0 4px;font-size:26px}@media(max-width:850px){.overview-grid{grid-template-columns:1fr}.stat-grid{grid-template-columns:repeat(2,1fr)}}@media(max-width:480px){.stat-grid{gap:10px}.stat-card{padding:14px}.stat-card strong{font-size:21px}}
</style></head><body><div class="admin-shell"><aside class="sidebar"><a class="brand" href="overview.php"><span class="brand-mark">E</span><span>Electra</span></a><p class="nav-label">Store management</p><nav class="side-nav"><a class="active" href="overview.php"><span>Overview</span></a><a href="products.php"><span>Products</span></a><a href="orders.php"><span>Orders</span></a><a href="payments.php"><span>Payments</span></a><a href="inventory.php"><span>Inventory</span></a></nav><p class="nav-label bottom-label">General</p><nav class="side-nav"><a href="index.php?view=settings"><span>Settings</span></a><a class="sign-out" href="logout.php"><span>Sign out</span></a></nav><div class="sidebar-foot"><i></i> Store online</div></aside><main class="workspace"><header class="workspace-header"><div><p class="kicker">Electra store</p><h1>Overview</h1></div><div class="profile"><span class="avatar"><?=overviewEscape(strtoupper(substr((string)$_SESSION['admin_name'],0,1)))?></span><span><strong><?=overviewEscape((string)$_SESSION['admin_name'])?></strong><small>Store manager</small></span></div></header><section class="page-heading"><div><p class="section-kicker">Your store at a glance</p><h2>Sales overview</h2><p>Confirmed revenue from the last six months.</p></div></section><section class="stat-grid"><article class="stat-card"><span>Confirmed revenue</span><strong>₦<?=number_format($revenue,2)?></strong><small>Paid orders</small></article><article class="stat-card"><span>Total orders</span><strong><?=$orderCount?></strong><small><?=$pending?> awaiting payment</small></article><article class="stat-card"><span>Customers</span><strong><?=$customerCount?></strong><small>Unique customer emails</small></article><article class="stat-card"><span>Store status</span><strong>Online</strong><small>Electra storefront active</small></article></section><section class="overview-grid"><article class="card chart-card"><div class="card-heading"><div><h2>Monthly sales</h2><p>Approved payment revenue</p></div><span class="select-pill">Last 6 months</span></div><div class="chart" aria-label="Sales revenue for the last six months"><?php foreach($months as $month):$height=$month['total']>0?max(5,($month['total']/$maxSales)*100):2;?><div class="bar-wrap"><div class="bar-area"><div><span class="chart-value">₦<?=number_format($month['total']/1000,1)?>k</span><i class="bar" style="height:<?=$height?>%"></i></div></div><small><?=overviewEscape($month['label'])?></small></div><?php endforeach;?></div></article><article class="card"><h2>Admin shortcuts</h2><p class="muted">Manage the parts of your store that need attention.</p><div class="overview-links"><a href="products.php">Manage products</a><a href="inventory.php">Check inventory</a><a href="orders.php">Review orders</a><a href="payments.php">Edit payments</a></div></article></section></main></div></body></html>
